// AgentBase.cs
using UnityEngine;
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine.Networking;
using Newtonsoft.Json;

[CreateAssetMenu(fileName = "Agent", menuName = "PSOC/Agents/Base Agent")]
public class AgentBase : PSOCQueryable
{
    [Header("Identification")]
    public string agentId;
    public string agentName;
    [TextArea] public string description;
    
    [Header("Configuration")]
    public List<ToolBase> tools;
    public LLMConfig llmConfig = new LLMConfig();

    [Header("Execution Settings")]
    [Range(1, 100)] public int maxIterations = 10;
    public bool verbose;
    
    [Header("Sync")]
    // When true this agent will be excluded from any bulk sync operations
    public bool excludeFromSync = false;
    
    [Header("Status")]
    public string status;
    public DateTime lastUpdated;
    
    /// <summary>
    /// A .md file containing the default prompt with instructions specific for this agent, use the keyword $USER_PROMPT$
    /// to specify the words that will be replaced with the users query. This default prompt will contain step by step instructions
    /// or similar agent instructions that will be mixed with a user request
    /// </summary>
    [Header("Default Prompt")]
    [SerializeField] public TextAsset promptTextFile;

    [Header("Rail Guarding")]
    public bool useRailGuarding = false;
    public TextAsset autoRailGuardingInputFile;
    public TextAsset railGuardingFile;
    
    // this method combines the user query with the default prompt text
    public string GetPromptText(string userQuery)
    {
        if (promptTextFile == null)
        {
            return "";
        }
        
        var defaultPrompt = promptTextFile.text;
        
        return defaultPrompt.Replace("$USER_PROMPT$", userQuery);
    }

    /// <summary>
    /// Calls the backend to get auto-generated rails for this agent based on its prompt
    /// </summary>
    [ContextMenu("Get Auto-Generated Rails")]
    public void GetAutoGeneratedRails()
    {
        // use connection settings and call the backend at url /v1/query/generate_rails_string
        var settings = ConnectionSettings.Instance;
        
        // we use this endpoint when there is no rail guarding input file, otherwise we use /v1/query/generate_rails_string_from_file
        var url_from_prompt = $"http://{settings.serverIP}:{settings.serverPort}/v1/query/generate_rails_string?agent_id={agentId}";
        var url_from_file = $"http://{settings.serverIP}:{settings.serverPort}/v1/query/generate_rails_string_2?input_text=";
        
        var url = "";
        if (autoRailGuardingInputFile == null)
        {
            url = url_from_prompt;
        }
        else
        {
            var inputText = UnityWebRequest.EscapeURL(autoRailGuardingInputFile.text);
            url = url_from_file + inputText;
        }
        
        var request = new UnityWebRequest(url, "GET");            
     
        request.downloadHandler = new DownloadHandlerBuffer();
        request.SetRequestHeader("Content-Type", "application/json");
        request.SendWebRequest();

        while (!request.isDone) { }
        if (request.result != UnityWebRequest.Result.Success)
        {
            Debug.LogError($"Error getting auto-generated rails: {request.error}");
            return;
        }
        // save the railguard string into a new TextAsset next to the current asset
        // the response is an json object with a field "rails_string"
        
        var responseDict = JsonConvert.DeserializeObject<Dictionary<string, object>>(request.downloadHandler.text);
        if (!responseDict.ContainsKey("rails_string"))
        {
            Debug.LogError("Error: Response does not contain 'rails_string'");
            return;
        }

        var response = responseDict["rails_string"].ToString();

        var path = AssetDatabase.GetAssetPath(this);
        var directory = System.IO.Path.GetDirectoryName(path);
        var railGuardingFilePath = System.IO.Path.Combine(directory, $"{agentName}_rails.xml");
        
        // create the text asset, if none is linked yet
        if (railGuardingFile == null)
            System.IO.File.WriteAllText(railGuardingFilePath, response);
        else
            System.IO.File.WriteAllText(AssetDatabase.GetAssetPath(railGuardingFile), response);
        AssetDatabase.Refresh();

        // load the text asset
        railGuardingFile = AssetDatabase.LoadAssetAtPath<TextAsset>(railGuardingFilePath);
        Debug.Log($"Auto-generated rails saved to {railGuardingFilePath}");
    }

}

// restrict this to be scriptable objects
public class PSOCQueryable : ScriptableObject
{
    
}

[Serializable]
public class LLMConfig
{
    public string modelName = "gpt-5.2-2025-12-11";
    [Range(0, 1)] public float temperature = 0.7f;
    public int maxTokens = 1000;
}
